### ISSUE TITLE
fix: setenv non-alphanum char in variable name test

### ISSUE THREAD

**Issue by RezaRahemtola** [RezaRahemtola/42sh#36]
Fix this test:
```json
{
    "name": "setenv - Var with non-alphanum chars",
    "command": "setenv va#r val"
}
```
which gives the right output manually:
![image](https://user-images.githubusercontent.com/49811529/168479517-e7dd5af0-b95c-465e-89ff-b5d4cfff652b.png)

but fails inside the functional tester (tcsh error message not detected):
![image](https://user-images.githubusercontent.com/49811529/168479556-db4a2bbf-45d2-44b6-9a4e-88762951a614.png)

**Comment by RezaRahemtola** [comment]
According to @Croos3r seems to be `tcsh` that doesn‘t display this error when using pipes (`echo "&&" | tcsh`)

**Comment by Croos3r** [comment]
Ouai c'est bibi qu'a trouvé

**Comment by Croos3r** [comment]
ty @RezaRahemtola

**Comment by Croos3r** [comment]
pls fix
