### ISSUE TITLE
feat: `.42shrc` file

### ISSUE THREAD

**Issue by RezaRahemtola** [RezaRahemtola/42sh#54]
- [ ] Alias
- [ ] Local env
- [ ] Env
- [ ] General commands

**Comment by EdenComp** [comment]
Why export? setenv exists

**Comment by RezaRahemtola** [comment]
> Why export? setenv exists

Yes, but look in your `.bashrc` you should have some `export PATH`
It's another way of doing it that we can support.

**Comment by RezaRahemtola** [comment]
First step is just to execute regular command, then we will look at `export`
